### PR TITLE
docs: add initial contributors

### PR DESCRIPTION
**Pull request by sanchitgera**

### CODE REVIEW

**Comment by msrose** [comment]
@sanchitgera Can we add Jeremy Sant as well, since he helped with the initial setup internally? https://github.com/JeremySant

**Comment by msrose** [comment]
Oh dang can we add @maryampaz for design as well 😅

**Comment by msrose** [comment]
Maryam not showing up, thing we need a `yarn contributors:generate`

**Comment by sanchitgera** [comment]
Done 🙏

**Pull request merged**
